// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygquzhldedfhetjnoflz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncXV6aGxkZWRmaGV0am5vZmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MTgzMTQsImV4cCI6MjA1NzA5NDMxNH0.Xn11roMRuaTrhDhLHN1_GF2SD-XSa2O17X7JQPOY8MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);